## Психометрика і важливість психологічних вимірювань

Ваше життя, ймовірно, частково формувалося під впливом психологічних вимірювань. Незалежно від того, чи ви студент, вчитель, батько, психолог, лікар, медсестра, пацієнт, юрист, поліцейський або бізнесмен, ви проходили психологічні тести, члени вашої родини проходили психологічні тести, або ви зазнавали впливу людей, які проходили психологічні тести. Ці тести можуть вплинути на нашу освіту, кар'єру, сімейне життя, безпеку, здоров'я, добробут і, можливо, на наше щастя. Дійсно, майже кожен член індустріального суспільства в певний момент свого життя зазнає впливу психологічних вимірювань — як прямо, так і опосередковано.

Можна навіть сказати, що в екстремальних ситуаціях психологічне вимірювання може мати наслідки, пов'язані з життям або смертю. Хоча це твердження може здатися надто сенсаційним, надуманим і, можливо, навіть просто помилковим, це правда. Справа в тому, що в деяких штатах і країнах правопорушники, які мають серйозні когнітивні розлади, не можуть бути засуджені до смертної кари. Наприклад, у штаті Північна Кароліна Генеральна Асамблея стверджує, що «жоден підсудний з розумовою неповносправністю не може бути засуджений до смертної кари» (N.C. Gen. Stat. § 15A-2005, 2019); він визначає інтелектуальну недостатність, зокрема, як загальне інтелектуальне функціонування, яке є «значно нижчим за середній рівень». Але що таке «значно нижче середнього» інтелектуальне функціонування, і як ми можемо дізнатися, чи дійсно інтелект людини є значно нижче середнього?

Відповіді на ці складні питання дають психологічні тести. Зокрема, Генеральна Асамблея стверджує, що значно нижчим за середній рівнем інтелектуального функціонування є показник 70 балів або нижче «за результатами індивідуально проведеного науково визнаного стандартизованого тесту на коефіцієнт інтелекту, що проводиться ліцензованим психіатром або психологом». Простіше кажучи, якщо людина має коефіцієнт інтелекту (IQ) нижче 70 балів, то вона не може бути засуджена до смертної кари в штаті Північна Кароліна; однак, якщо людина має IQ вище 70, то вона може бути законно засуджена до смертної кари. Таким чином, хоча в це важко повірити, тестування інтелекту може впливати на те, жити чи померти людині у буквальному сенсі цього слова. Звичайно, небагато наслідків психологічних вимірювань є настільки драматичними, але вони дійсно можуть бути реальними, довготривалими і важливими.

Враховуючи важливу роль психологічних тестів у нашому житті та суспільстві загалом, ці тести повинні мати надзвичайно високу якість. Якщо тестування має такі серйозні наслідки, то воно повинно проводитися за допомогою найсучасніших інструментів і процедур.

Ця книга присвячена розумінню того, чи дійсно такі інструменти та процедури є надійними – як визначити, чи дає тест психологічно значущі та достовірні результати. Крім того, принципи та концепції, розглянуті в цій книзі, важливі для створення тестів, які є психологічно значущими та достовірними. Ці принципи та концепції відомі як психометрика.

## ЧОМУ ПСИХОЛОГІЧНЕ ТЕСТУВАННЯ ВАЖЛИВЕ ДЛЯ ВАС

Враховуючи потенційний вплив психологічного тестування на реальне життя, вам необхідно розуміти основні принципи психологічних вимірювань. Незалежно від того, чи хочете ви бути практиком в галузі поведінкових наук, дослідником поведінки або досвідченим членом сучасного суспільства, психологічні вимірювання, швидше за все, вплинуть на ваше життя.

Можливо, ви розглядаєте кар'єру, пов'язану з психологічними вимірюваннями. Дехто з вас може розглядати кар'єру в галузі практичної або прикладної науки про поведінку. Незалежно від того, чи є ви клінічним психологом, шкільним психологом, директором з управління персоналом, членом приймальної комісії університету або вчителем, ваша робота може вимагати прийняття рішень на основі результатів, отриманих за допомогою психологічних тестів. Коли пацієнт відповідає на запитання психопатологічного тесту, коли студент заповнює тест на когнітивні або академічні здібності, або коли претендент на роботу заповнює особистісний запитальник, відбувається спроба виміряти певну психологічну характеристику.

У таких випадках користувачі тестів несуть відповідальність за вивчення та інтерпретацію важливої інформації про значення та якість тестів, які вони використовують. Без ґрунтовного розуміння основних принципів психологічних вимірювань користувачі тестів ризикують неправильно інтерпретувати або використовувати інформацію, отриману за допомогою психологічних тестів. Таке неправильне тлумачення або використання може зашкодити пацієнтам, студентам, клієнтам, працівникам та абітурієнтам, а також призвести до судових позовів проти користувача тесту. Правильна інтерпретація та використання тестів може бути надзвичайно цінною для користувачів тестів і корисною для учасників тестування.

Дехто з вас, можливо, розглядає кар'єру в галузі поведінкових досліджень. Незалежно від того, чи ви займаєтеся психологією, педагогікою або будь-якою іншою поведінковою наукою, вимірювання лежить в основі вашого дослідницького процесу. Незалежно від того, чи проводите ви експериментальні дослідження, опитування чи будь-який інший вид кількісних досліджень, вимірювання є основою вашого дослідницького процесу. Якщо вас цікавлять відмінності між людьми, зміни в людях з плином часу, відмінності між статями, відмінності між класами, відмінності між умовами лікування, відмінності між вчителями або відмінності між культурами, вимірювання лежить в основі вашого дослідницького процесу. Якщо щось не вимірюється або вимірюється погано, то воно не може бути вивчене з науковою достовірністю. Якщо ваша мета - змістовна і точна інтерпретація результатів дослідження, то ви повинні критично оцінити вимірювання, які ви зібрали в ході дослідження.

Як згадувалося вище, навіть якщо ви не пов'язуєте свою кар'єру з психологічними вимірюваннями, ви майже напевно зіткнетеся з наслідками психологічних вимірювань, прямо чи опосередковано. Вступники до аспірантури та різних професійних шкіл можуть бути прийняті (або не прийняті) частково на основі тестів на знання та досягнення. Претенденти на роботу можуть бути прийняті (або не прийняті) на роботу частково на основі результатів особистісних тестів. Працівників можуть підвищувати (або не підвищувати) частково на основі оцінок керівником психологічних характеристик, таких як ставлення, компетентність або колегіальність. Батьки повинні справлятися з наслідками освітнього тестування своїх дітей. Людей, які звертаються за психологічною допомогою, можуть діагностувати та лікувати частково на основі їхніх відповідей на різні психологічні тести.

Навіть ширше, наше суспільство отримує інформацію та рекомендації, засновані на результатах досліджень. Незалежно від того, чи ви є (або будете) абітурієнтом, працівником, батьком, клієнтом психолога або поінформованим членом суспільства, чим більше ви знаєте про психологічні вимірювання, тим більш поінформованим споживачем ви будете.

Ви будете краще розуміти, коли слід приймати або вірити результатам тесту, коли слід ставити під сумнів використання та інтерпретацію результатів тесту, а також що вам потрібно знати для прийняття таких важливих рішень.

Зважаючи на широке використання та важливість психологічних вимірювань, вкрай важливо розуміти властивості, що впливають на якість таких вимірювань. У цій книжці йдеться про важливі характеристики інструментів, які психологи використовують для вимірювання психологічних властивостей і процесів.

У цій книзі розглядається кілька фундаментальних питань, пов'язаних з логікою, розробкою, оцінкою та використанням психологічних заходів.
