# Передмова {.unnumbered}

Вимірювання лежить в основі будь-якої науки і всіх її застосувань. Це справедливо для всіх галузей науки, включаючи наукове вивчення людської поведінки. Поведінкові дослідження, незалежно від того, чи проводяться вони педагогами, психологами чи іншими соціальними науковцями, залежать від успішного вимірювання людської поведінки або психологічних характеристик, які, як вважається, впливають на цю поведінку. Аналогічно, застосування психологічної чи педагогічної науки часто значною мірою залежить від успішного вимірювання. Дійсно, науково обґрунтовані клінічні або освітні програми та втручання вимагають вимірювання поведінки або психологічних особливостей людей, які беруть участь у цих програмах.

Ця книга присвячена методам оцінювання якості вимірювальних інструментів, таких як психологічні тести, які використовуються в дослідницьких і прикладних цілях психологами та іншими фахівцями, що цікавляться людською поведінкою. Наукове вивчення якості психологічних вимірювань називається психометрією. Психометрія є надзвичайно важливою галуззю дослідження, і вона може бути дуже технічною.

У статті, опублікованій в New York Times (Herszenhorn, 2006), стверджується, що "психометрія, одна з найбільш незрозумілих, езотеричних і мозкових професій в Америці, також є однією з найгарячіших".
